--------------------------------------------------------
--  File created - Saturday-May-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANQ_REGISTER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ANQ_REGISTER" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"DOB" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"PICTURE" VARCHAR2(500 BYTE), 
	"MOBILENO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ANQ_REGISTER
SET DEFINE OFF;
Insert into SYSTEM.ANQ_REGISTER (ID,USERNAME,PASSWORD,EMAIL,ADDRESS,DOB,GENDER,PICTURE,MOBILENO) values (7,'abhi','1234','abhi.galipally@gmail.com','9908432736',null,null,'Male','IMG_20190620_004702_957.jpg');
Insert into SYSTEM.ANQ_REGISTER (ID,USERNAME,PASSWORD,EMAIL,ADDRESS,DOB,GENDER,PICTURE,MOBILENO) values (8,'nani','1234','nani@gmail.com','hyd',null,'Male','IMG_20200213_165605_1.jpg','7799582662');
Insert into SYSTEM.ANQ_REGISTER (ID,USERNAME,PASSWORD,EMAIL,ADDRESS,DOB,GENDER,PICTURE,MOBILENO) values (9,'nani','1234','nani@gmail.com','hyd',null,'Male','IMG_20200213_165605_1.jpg','7799582662');
Insert into SYSTEM.ANQ_REGISTER (ID,USERNAME,PASSWORD,EMAIL,ADDRESS,DOB,GENDER,PICTURE,MOBILENO) values (10,'charan','1234','charan@gmail.com','		hyd		','05/02/1997','Male','IMG_20200213_165605_1.jpg','9908432736');
--------------------------------------------------------
--  DDL for Index ANQ_REGISTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ANQ_REGISTER_PK" ON "SYSTEM"."ANQ_REGISTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ANQ_REGISTER_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ANQ_REGISTER_TRG1" 
BEFORE INSERT ON ANQ_REGISTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."ANQ_REGISTER_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ANQ_REGISTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ANQ_REGISTER_TRG" 
BEFORE INSERT ON ANQ_REGISTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."ANQ_REGISTER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ANQ_REGISTER_TRG3
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ANQ_REGISTER_TRG3" 
BEFORE INSERT ON ANQ_REGISTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ANQ_REGISTER_SEQ3.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."ANQ_REGISTER_TRG3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ANQ_REGISTER_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ANQ_REGISTER_TRG2" 
BEFORE INSERT ON ANQ_REGISTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."ANQ_REGISTER_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table ANQ_REGISTER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANQ_REGISTER" ADD CONSTRAINT "ANQ_REGISTER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ANQ_REGISTER" MODIFY ("ID" NOT NULL ENABLE);
